import React from 'react';
import LegalPageShell, { Section } from './LegalPageShell';

const Disclaimer = () => (
  <LegalPageShell title="Risk Disclosure & Disclaimer" updated="August 2026">
    <p style={{ marginBottom: '24px' }}>
      This Risk Disclosure and Disclaimer ("Disclaimer") is an integral part of the KYNEX User
      Agreement and must be read in conjunction with all other legal documentation published on this
      platform. By using KYNEX, you acknowledge that you have read, understood, and accepted all
      provisions set forth below.
    </p>

    <Section title="Article 1 — General Risk Warning">
      <p>
        Trading in digital assets (cryptocurrencies, tokens, and related instruments) involves a
        high degree of risk and is not suitable for all investors. The value of digital assets is
        extremely volatile and can fluctuate significantly within very short periods. You should
        carefully consider whether trading or holding digital assets is appropriate for you in light
        of your financial condition, investment experience, and risk tolerance. You should only
        trade with funds that you can afford to lose entirely without affecting your financial
        security or lifestyle.
      </p>
    </Section>

    <Section title="Article 2 — No Guaranteed Returns">
      <p>
        KYNEX does not guarantee, represent, or warrant that any trade, strategy, or investment
        will result in profits or will not result in losses. Past performance of any digital asset,
        trading signal, or analytical tool provided on the platform is not indicative of future
        results. No representation is being made that any account will or is likely to achieve
        profits or losses similar to those discussed, displayed, or implied on KYNEX. Historical
        returns, expected returns, and probability projections are provided for informational
        purposes only and may not reflect actual future performance.
      </p>
    </Section>

    <Section title="Article 3 — No Financial, Investment, or Legal Advice">
      <p>
        Nothing contained on the KYNEX platform — including but not limited to market data, price
        charts, trading signals, analytical tools, news feeds, educational content, or any other
        information — constitutes financial, investment, tax, legal, or other professional advice.
        All content is provided for informational and educational purposes only. KYNEX is not a
        registered investment adviser, broker-dealer, or financial planner in any jurisdiction.
        You should consult with qualified, licensed professionals before making any financial
        decisions.
      </p>
    </Section>

    <Section title="Article 4 — Market & Volatility Risk">
      <p>
        Digital asset markets operate continuously (24/7) and are subject to rapid, unpredictable
        price movements. The following risks, among others, apply to all digital asset trading:
      </p>
      <ul style={{ margin: '10px 0 0 0', paddingLeft: '20px' }}>
        <li>Prices can decline sharply and without warning, potentially reaching zero</li>
        <li>Market liquidity can vary significantly, which may affect order execution</li>
        <li>Regulatory actions in any jurisdiction may impact asset values or availability</li>
        <li>Technological failures, including smart contract bugs or protocol vulnerabilities, may cause irreversible loss</li>
        <li>Market manipulation and fraudulent schemes may exist in digital asset markets</li>
        <li>Forks, airdrops, and protocol changes may affect your holdings without prior notice</li>
      </ul>
    </Section>

    <Section title="Article 5 — Leverage & Futures Trading Risk">
      <p>
        Trading leveraged instruments, including perpetual futures contracts, carries substantially
        higher risk than spot trading. Leverage amplifies both potential gains and potential losses.
        You may lose more than your initial margin deposit. Liquidation of your position may occur
        automatically if your margin falls below maintenance requirements. KYNEX strongly advises
        that only experienced traders with a thorough understanding of leverage mechanics engage in
        futures trading. By using leverage features, you acknowledge and accept that you may incur
        losses that exceed your deposited funds.
      </p>
    </Section>

    <Section title="Article 6 — Trading Signal Disclaimer">
      <p>
        Trading signals provided on KYNEX are generated by proprietary algorithms and analytical
        models. These signals are informational tools only and do not constitute recommendations,
        solicitations, or offers to buy or sell any digital asset. Signal accuracy is not guaranteed,
        and historical signal performance does not predict future results. Market data used for
        signal generation may be subject to processing delays. Users should exercise independent
        judgment and perform their own analysis before executing any trade.
      </p>
    </Section>

    <Section title="Article 7 — Limitation of Liability">
      <p>
        To the maximum extent permitted by applicable law, KYNEX, its affiliates, directors,
        officers, employees, agents, and licensors shall not be liable for any direct, indirect,
        incidental, special, consequential, or punitive damages arising from or related to:
      </p>
      <ul style={{ margin: '10px 0 0 0', paddingLeft: '20px' }}>
        <li>Your use of or inability to use the Services</li>
        <li>Any trading decisions made based on information available on the platform</li>
        <li>Unauthorized access to or alteration of your data or transactions</li>
        <li>Interruption, suspension, or termination of the Services</li>
        <li>Losses resulting from technological failures, including but not limited to blockchain network congestion, smart contract failures, or wallet address errors</li>
        <li>Losses arising from disputes between Customers in peer-to-peer transactions</li>
        <li>Price discrepancies between KYNEX and other exchanges or data providers</li>
        <li>Actions taken by regulatory authorities affecting access to or value of digital assets</li>
      </ul>
    </Section>

    <Section title="Article 8 — Force Majeure">
      <p>
        KYNEX shall not be held liable for any delay, failure, or interruption of the Services
        resulting from events beyond our reasonable control, including but not limited to:
      </p>
      <ul style={{ margin: '10px 0 0 0', paddingLeft: '20px' }}>
        <li>Natural disasters, epidemics, pandemics, or acts of God</li>
        <li>War, armed conflict, terrorism, civil unrest, or sanctions</li>
        <li>Government actions, regulatory changes, or embargoes</li>
        <li>Failures of third-party telecommunications, cloud hosting, or internet infrastructure</li>
        <li>Cyberattacks, distributed denial-of-service (DDoS) attacks, or data breaches affecting third-party providers</li>
        <li>Blockchain network congestion, hard forks, or protocol-level failures</li>
        <li>Scheduled or emergency maintenance of our systems</li>
        <li>Power outages or equipment failures beyond our control</li>
      </ul>
    </Section>

    <Section title="Article 9 — Service Availability & Data Accuracy">
      <p>
        While KYNEX uses commercially reasonable efforts to ensure platform availability and data
        accuracy, we do not warrant that the Services will be uninterrupted, error-free, or that
        market data will be delivered without delay. Real-time market data is sourced from
        third-party providers and may be subject to delays, inaccuracies, or temporary
        unavailability. KYNEX is not responsible for losses incurred due to reliance on delayed
        or inaccurate market data.
      </p>
    </Section>

    <Section title="Article 10 — Device & Network Security">
      <p>
        You are solely responsible for the security of the devices, networks, and software you use
        to access KYNEX. KYNEX is not liable for losses resulting from malware, viruses,
        phishing attacks, keyloggers, or other malicious software affecting your devices.
        You are responsible for ensuring that your internet connection is secure and that
        your device's operating system and browser are up to date with the latest security patches.
      </p>
    </Section>

    <Section title="Article 11 — Tax Obligations">
      <p>
        You are solely responsible for determining what, if any, taxes apply to the transactions
        you conduct through KYNEX, and for reporting and remitting the correct tax amounts to
        the appropriate tax authorities. KYNEX does not provide tax advice and is not responsible
        for determining whether taxes apply to your trades, or for collecting, reporting, or
        remitting any taxes arising from any transactions.
      </p>
    </Section>

    <Section title="Article 12 — Regulatory Risk">
      <p>
        The regulatory landscape for digital assets is rapidly evolving across jurisdictions.
        Changes in laws, regulations, or government policies may adversely affect the use,
        transfer, exchange, or value of digital assets. KYNEX may be required to modify, suspend,
        or discontinue certain services or features to comply with applicable regulations,
        potentially with limited or no advance notice. Such regulatory actions may affect your
        ability to access or withdraw your assets.
      </p>
    </Section>

    <Section title="Article 13 — Irreversibility of Blockchain Transactions">
      <p>
        Transactions on blockchain networks are generally irreversible once confirmed. If you
        send digital assets to an incorrect address, use the wrong network, or send an
        unsupported token, KYNEX may not be able to recover those assets. You are solely
        responsible for verifying all transaction details — including wallet addresses, network
        selection, and asset type — before initiating any transfer.
      </p>
    </Section>

    <Section title="Article 14 — Third-Party Links & Services">
      <p>
        KYNEX may contain links to third-party websites, applications, or services. These links
        are provided for convenience only and do not imply endorsement, sponsorship, or
        affiliation. KYNEX is not responsible for the content, accuracy, security, or privacy
        practices of any third-party website or service. Your use of third-party services is at
        your own risk and subject to the terms and policies of those third parties.
      </p>
    </Section>

    <Section title="Article 15 — Indemnification">
      <p>
        You agree to indemnify, defend, and hold harmless KYNEX, its affiliates, officers,
        directors, employees, and agents from and against any and all claims, damages, losses,
        liabilities, costs, and expenses (including reasonable legal fees) arising from or related
        to your use of the Services, your violation of this Disclaimer or any applicable law, or
        your violation of any rights of a third party.
      </p>
    </Section>

    <Section title="Article 16 — Governing Law & Dispute Resolution">
      <p>
        This Disclaimer shall be governed by and construed in accordance with the laws of
        Switzerland. Any dispute arising out of or in connection with this Disclaimer shall be
        submitted to the exclusive jurisdiction of the courts of the Canton of Zurich, Switzerland,
        unless mandatory consumer protection laws in your jurisdiction require otherwise. Before
        initiating formal proceedings, both parties agree to attempt resolution through KYNEX's
        internal complaints procedure.
      </p>
    </Section>

    <Section title="Article 17 — Severability">
      <p>
        If any provision of this Disclaimer is found to be unlawful, void, or unenforceable by a
        court of competent jurisdiction, such provision shall be deemed severed from this Disclaimer
        and shall not affect the validity or enforceability of the remaining provisions, which shall
        continue in full force and effect.
      </p>
    </Section>

    <Section title="Article 18 — Acknowledgment">
      <p>
        By accessing or using KYNEX, you confirm that you have read this Risk Disclosure and
        Disclaimer in its entirety, that you understand the risks associated with digital asset
        trading, and that you accept all terms and conditions set forth herein. If you do not agree
        with any part of this Disclaimer, you must immediately cease using the KYNEX platform.
      </p>
    </Section>
  </LegalPageShell>
);

export default Disclaimer;
